version: '3.8'

services:
  app:
    image: sinebii/agribridge:latest
    container_name: agribridge_app
    restart: always
    ports:
      - "7081:7081"
    environment:
      - SPRING_DATASOURCE_URL=${AGRIBRIDGE_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${AGRIBRIDGE_DB_CREDENTIALS_USR}
      - SPRING_DATASOURCE_PASSWORD=${AGRIBRIDGE_DB_CREDENTIALS_PSW}
